openapi: 3.0.0
info:
  version: 1.0.0
  title: API 문서
  description: SUI Marketplace API
  license:
    name: MIT
servers:
  - url: 'http://localhost:3000'
paths:
  /ping:
    get:
      summary: 헬스 체크
      description: 서버가 살아있는지 확인합니다.
      responses:
        '200':
          description: 성공 응답
